version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn run generate
  post_build:
    commands:
      - aws s3 sync dist s3://$DEPLOY_S3_BUCKET --acl public-read --delete --cache-control 'public, max-age=300'
